[package]
name = "tcpk-common"
version = "0.1.0"
edition = "2021"

[features]
default = []

[dependencies]
aya-bpf = { git = "https://github.com/aya-rs/aya" }
libc = { version = "0.2", features = [] }

[lib]
path = "src/lib.rs"
